# Generated by Django 3.1.3 on 2020-11-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_auto_20201115_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(default=False, upload_to='uploads/'),
        ),
    ]
